### PR TITLE
	modified:   chronos-app/app/(tabs)/Home.tsx

### PR DESCRIPTION
**Pull request by not-good-keeper**
new file:   package-lock.json

### CODE REVIEW

**Comment by not-good-keeper** [comment]
ive changed the homepage a bit, and only the homepage and package-lock are the files im commiting

**Review by vijay-sb — APPROVED** [review]
**Few Suggestions**

1. **Flatlist** - Use Flatlist for rendering Tasks instead of map function

2. Use NativeWind classes for styling

3. Can we have some better icons for this?

image

4. Try adding some horizontal or vertical lines for a better look
image

5.Add a conditional styling to highlight todays date

**Comment by IAmRiteshKoushik** [comment]
@KiranRajeev-KV take a look at this at your earliest and wrap it up please. Work on `chronos` has had a hard stall post-WoC initiation. We need to get back on track.

**Review by KiranRajeev-KV — APPROVED** [review]
Looks good.

**Pull request merged**
